baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'liblouis'
theme = 'hugo-book'

[params]
BookSearch = false
BookComments = false
BookMenuBundle = '/menu'
BookSection = '/'
BookLogo = 'logo.png'
